// Fields that can be printed in the employee file PDF (value = key sent to the API).
export const FILE_FIELDS = [
  { value: 'employee_id_number', label: 'رقم الموظف' },
  { value: 'full_name', label: 'الاسم الكامل' },
  { value: 'first_name', label: 'الاسم الأول' },
  { value: 'second_name', label: 'الاسم الثاني' },
  { value: 'third_name', label: 'الاسم الثالث' },
  { value: 'fourth_name', label: 'الاسم الرابع' },
  { value: 'branch_id', label: 'الفرع' },
  { value: 'job_title', label: 'المسمى الوظيفي' },
  { value: 'nationality', label: 'الجنسية' },
  { value: 'date_of_birth_hijri', label: 'تاريخ الميلاد (هجري)' },
  { value: 'date_of_birth_gregorian', label: 'تاريخ الميلاد (ميلادي)' },
  { value: 'age', label: 'العمر' },
  { value: 'id_or_residency_number', label: 'رقم الهوية/الإقامة' },
  { value: 'id_type', label: 'نوع الهوية' },
  { value: 'gender', label: 'الجنس' },
  { value: 'id_expiry_date_hijri', label: 'تاريخ انتهاء الهوية (هجري)' },
  { value: 'id_expiry_date_gregorian', label: 'تاريخ انتهاء الهوية (ميلادي)' },
  { value: 'religion', label: 'الديانة' },
  { value: 'marital_status', label: 'الحالة الاجتماعية' },
  { value: 'educational_qualification', label: 'المؤهل التعليمي' },
  { value: 'specialization', label: 'التخصص' },
  { value: 'bank_iban', label: 'الآيبان' },
  { value: 'bank_name', label: 'اسم البنك' },
  { value: 'email', label: 'البريد الإلكتروني' },
  { value: 'phone_number', label: 'رقم الهاتف' },
  { value: 'national_address', label: 'العنوان الوطني' },
  { value: 'contract_type', label: 'نوع العقد' },
  { value: 'years_of_experience_in_same_institution', label: 'سنوات الخبرة في نفس المؤسسة' },
  { value: 'years_of_experience_in_company', label: 'سنوات الخبرة في الشركة' },
  { value: 'salary', label: 'الراتب' },
  { value: 'base_salary', label: 'الراتب الأساسي' },
  { value: 'housing_allowance', label: 'بدل السكن' },
  { value: 'transportation_allowance', label: 'بدل المواصلات' },
  { value: 'end_of_service_allowance', label: 'بدل نهاية الخدمة' },
  { value: 'annual_leave_allowance', label: 'بدل الإجازة السنوية' },
  { value: 'other_allowances', label: 'بدلات أخرى' },
  { value: 'graduation_year', label: 'سنة التخرج' },
  { value: 'university_gpa', label: 'المعدل التراكمي' },
  { value: 'passport_number', label: 'رقم الجواز' },
  { value: 'passport_issue_date', label: 'تاريخ إصدار الجواز' },
  { value: 'passport_expiry_date', label: 'تاريخ انتهاء الجواز' },
  { value: 'passport_issue_place', label: 'مكان إصدار الجواز' },
  { value: 'residency_issue_date', label: 'تاريخ إصدار الإقامة' },
  { value: 'data_completion_status', label: 'حالة إكمال البيانات' },
];

export const DEFAULT_FILE_FIELDS = ['full_name', 'employee_id_number', 'id_or_residency_number', 'nationality'];
